title: Stackbit Fjord Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
palette: yellow
header:
  title: Albirar.cat
  tagline: 'Software Architect, Fullstack designer & developer, Agile specialist'
  logo_img: images/logocat-646x220-lletres-verdes.png
  logo_img_alt: Albirar logo
  background_img: images/foto original.jpg
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: lorem-ipsum
      url: '#'
      style: link
      icon_class: dev
      new_window: false
      no_follow: false
      type: action
    - label: About
      url: /about
      style: link
    - label: Style Guide
      url: /style-guide
      style: link
    - label: Contact
      url: /contact
      style: link
    - label: lorem-ipsum
      url: '#'
      style: link
      icon_class: dev
      new_window: false
      no_follow: false
      type: action
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      style: icon
      icon_class: twitter
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/'
      style: icon
      icon_class: instagram
      new_window: true
    - label: GitHub
      url: 'https://github.com/'
      style: icon
      icon_class: github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: icon
      icon_class: linkedin
      new_window: true
    - label: DEV
      url: 'https://dev.to/'
      style: icon
      icon_class: dev
      new_window: true
footer:
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>. Create yours <a
    href="https://app.stackbit.com/create?theme=fjord&utm_source=deployed-footer"
    target="_blank" rel="noopener">now</a>
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://friendly-mint-d1e00.netlify.app'
